language: python
python:
  - "2.7"

node_js: 6

cache:
  directories:
    - $HOME/edxapp_toxenv/
  pip: true
  npm: true

before_install:
  - sudo rm -f /etc/boto.cfg
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install python-dev libxml2-dev libxmlsec1-dev

install:
  - pip install tox

env:
  - TOXENV=pep8
  - TOXENV=py27-django111
    ARGS="-- paver run_pep8"

script:
  - tox $ARGS
